"""Add role column to admins

Revision ID: 7dd38d211cbe
Revises: 
Create Date: 2025-04-02 13:00:22.470115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd38d211cbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('role', sa.String(), nullable=False))
    op.alter_column('member_logins', 'member_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_logins', 'member_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('admin', 'role')
    # ### end Alembic commands ###
